# This is a sample .codeclimate.yml configured for Engine analysis on Code
# Climate Platform. For an overview of the Code Climate Platform, see here:
# http://docs.codeclimate.com/article/300-the-codeclimate-platform

# Under the engines key, you can configure which engines will analyze your repo.
engines:
  csslint:
    enabled: true
  eslint:
    enabled: true
    config:
      extensions:
      - .es6
      - .js
      - .jsx
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
  - src/**
exclude_paths:
- node_modules/**
- public/**
- tests/**/*