engines:
  csslint:
    enabled: true
  eslint:
    enabled: true
    config:
      extensions:
      - .es6
      - .js
      - .jsx
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
  - src/**
exclude_paths:
- node_modules/**
- public/**
- test/**/*